### PR TITLE
[feat]: add estimation price again inside input warehouse

### PR DESCRIPTION
**Pull request by MauladaniAdiG**
### Overview
- add estimation price again inside input warehouse

### CODE REVIEW

**Comment by nandaprasesoft98** [comment]
yang ini mas bisa dimerge?

**Comment by MauladaniAdiG** [comment]
darimu aman nda mas wkkwkw?

**Comment by nandaprasesoft98** [comment]
ok

**Review by nandaprasesoft98 — APPROVED** [review]

**Comment by nandaprasesoft98** [comment]
wait i have to review this again before merging

**Pull request merged**
